"use client";
import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { apiRequest } from "@/lib/api/client";

type Source = { id: string; name: string; source_type: string; content: string; source_url: string | null; status: string; created_at: string };
export default function KnowledgePage() { const [sources, setSources] = useState<Source[]>([]); const [open, setOpen] = useState(false); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [form, setForm] = useState({ name: "", sourceType: "text", content: "", sourceUrl: "" });
  function load() { setLoading(true); apiRequest<Source[]>("/api/knowledge").then(setSources).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }
  useEffect(() => { apiRequest<Source[]>("/api/knowledge").then(setSources).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  async function add(event: FormEvent) { event.preventDefault(); setError(""); try { await apiRequest("/api/knowledge", { method: "POST", body: JSON.stringify({ ...form, sourceUrl: form.sourceUrl || null }) }); setOpen(false); setForm({ name: "", sourceType: "text", content: "", sourceUrl: "" }); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add knowledge"); } }
  async function remove(id: string) { if (!window.confirm("Delete this knowledge source?")) return; try { await apiRequest(`/api/knowledge/${id}`, { method: "DELETE" }); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to delete source"); } }
  return <main className="phone-shell feature-page"><header className="app-header"><Link href="/" className="brand"><span className="brand-name">Hands<span>Free</span></span><span className="brand-parent">by VoiceDesk Technologies</span></Link><Link className="feature-back" href="/">Back to phone</Link></header><section className="feature-content"><div className="feature-heading"><div><span className="eyebrow">AGENT CONTEXT</span><h1>Knowledge Base</h1><p className="lead-copy">Give your agents reliable information to use during calls.</p></div><button className="primary-action feature-action" onClick={() => setOpen(true)}>Add knowledge <span>+</span></button></div>{error && <p className="auth-error">{error}</p>}{loading ? <p className="feature-muted">Loading knowledge sources...</p> : sources.length === 0 ? <div className="empty-state"><h2>No knowledge sources yet.</h2><p>Add notes or a website your agents can reference.</p><button className="primary-action" onClick={() => setOpen(true)}>Add your first source <span>→</span></button></div> : <div className="contact-list">{sources.map((source) => <article className="contact-row" key={source.id}><span className="agent-avatar">▤</span><div><h2>{source.name}</h2><p>{source.source_type.toUpperCase()} · {source.status}</p><small>{source.source_type === "url" ? source.source_url : `${source.content.length.toLocaleString()} characters`} · {new Date(source.created_at).toLocaleDateString()}</small></div><button className="row-delete" onClick={() => remove(source.id)} aria-label={`Delete ${source.name}`}>×</button></article>)}</div>}</section>{open && <div className="modal-layer"><form className="call-modal" onSubmit={add}><button type="button" className="modal-close" onClick={() => setOpen(false)} aria-label="Close">×</button><span className="eyebrow">NEW SOURCE</span><h1>Add knowledge</h1><label>Name<input value={form.name} onChange={(event) => setForm({ ...form, name: event.target.value })} required /></label><label>Type<select value={form.sourceType} onChange={(event) => setForm({ ...form, sourceType: event.target.value })}><option value="text">Text or notes</option><option value="url">Website URL</option></select></label>{form.sourceType === "text" ? <label>Content<textarea value={form.content} onChange={(event) => setForm({ ...form, content: event.target.value })} minLength={1} required /></label> : <label>Website URL<input type="url" value={form.sourceUrl} onChange={(event) => setForm({ ...form, sourceUrl: event.target.value })} required /></label>}<button className="primary-action">Save source <span>→</span></button></form></div>}</main>; }
