"use client";

import { FormEvent, useState } from "react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/api/client";

export default function CreateAgentPage() {
  const router = useRouter(); const [form, setForm] = useState({ name: "", role: "Personal Assistant", personality: "Friendly", greeting: "Hi, I'm an AI assistant calling on behalf of HandsFree.", systemInstructions: "Speak naturally, keep responses concise, ask one question at a time, and never make promises you cannot fulfill." }); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { await apiRequest("/api/agents", { method: "POST", body: JSON.stringify({ ...form, disclosureEnabled: true, disclosureText: form.greeting }) }); router.push("/agents"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to create agent"); setLoading(false); } }
  return <main className="phone-shell feature-page"><header className="app-header"><Link href="/" className="brand"><span className="brand-name">Hands<span>Free</span></span><span className="brand-parent">by VoiceDesk Technologies</span></Link><Link className="feature-back" href="/agents">Cancel</Link></header><form className="feature-content form-page" onSubmit={submit}><span className="eyebrow">AGENT BUILDER</span><h1>Create an AI agent</h1><label>Agent name<input value={form.name} onChange={(event) => update("name", event.target.value)} placeholder="Sarah" required /></label><label>Role<input value={form.role} onChange={(event) => update("role", event.target.value)} required /></label><label>Personality<select value={form.personality} onChange={(event) => update("personality", event.target.value)}><option>Professional</option><option>Friendly</option><option>Warm</option><option>Direct</option><option>Empathetic</option></select></label><label>Greeting<textarea value={form.greeting} onChange={(event) => update("greeting", event.target.value)} required /></label><label>System instructions<textarea value={form.systemInstructions} onChange={(event) => update("systemInstructions", event.target.value)} required /></label>{error && <p className="auth-error">{error}</p>}<button className="primary-action" disabled={loading}>{loading ? "Creating agent..." : "Create agent"}<span>→</span></button></form></main>;
}