import Link from "next/link";
import DemoForm from "@/components/DemoForm";

const roles = [
  ["Sales Agent", "Understand prospects, answer questions, and move qualified conversations forward."],
  ["Customer Service", "Resolve common questions with patience, context, and clear next steps."],
  ["Booking Agent", "Schedule, confirm, and reschedule appointments over a natural conversation."],
  ["Receptionist", "Answer the first call, identify intent, route callers, and take messages."],
  ["Lead Qualification", "Ask the right questions and surface the opportunities worth a follow-up."],
  ["Support Agent", "Troubleshoot known issues and bring a human in when the situation needs one."],
];

export default function LandingPage() {
  return <main className="public-site">
    <nav className="public-nav"><Link href="/" className="public-brand">HAND<span>SFREE</span><small>by VoiceDesk Technologies</small></Link><div className="public-links"><a href="#product">Product</a><a href="#roles">Solutions</a><a href="#how-it-works">How it works</a><a href="#pricing">Pricing</a><a href="#demo">Book a Demo</a></div><div className="public-nav-actions"><Link href="/auth/login" className="text-link">Sign in</Link><a href="#demo" className="button button-dark">Book a Demo <span>↗</span></a></div></nav>
    <section className="public-hero" id="product"><div className="hero-copy"><p className="public-kicker">AI PHONE AGENTS FOR MODERN BUSINESSES</p><h1>AI that works<br /><em>for your business.</em></h1><p className="hero-lead">Let HANDSFREE handle the calls, conversations, and follow-ups that keep your business moving.</p><div className="hero-actions"><a href="#demo" className="button button-dark">Book a Demo <span>↗</span></a><a href="#how-it-works" className="button button-quiet">See how it works <span>↓</span></a></div><p className="hero-note">Real phone conversations. Your instructions. A better way to stay responsive.</p></div><div className="hero-visual"><img src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=1200&q=85" alt="Business team collaborating around a phone call" /><div className="call-overlay"><span className="live-dot" /> HANDSFREE LIVE <strong>AI agent is speaking</strong><p>“I can help you find a time that works.”</p><small>Customer service · 00:42</small></div></div></section>
    <div className="capability-marquee" aria-label="HANDSFREE capabilities"><div><span>SALES</span><i>✦</i><span>CUSTOMER SERVICE</span><i>✦</i><span>APPOINTMENT BOOKING</span><i>✦</i><span>LEAD QUALIFICATION</span><i>✦</i><span>OUTBOUND CALLING</span><i>✦</i><span>INBOUND CALLING</span><i>✦</i><span>AI PHONE AGENTS</span><i>✦</i></div></div>
    <section className="public-section intro-section"><p className="public-kicker">MORE THAN A CHATBOT</p><h2>Your business should not have to stop every time the phone rings.</h2><p>HANDSFREE gives your team an AI phone agent that talks to real people, listens to what they need, follows your business instructions, and knows when to bring in a human.</p></section>
    <section className="public-section role-section" id="roles"><div className="section-heading"><div><p className="public-kicker">ONE AI. MANY ROLES.</p><h2>Give your AI a job<br />and a purpose.</h2></div><p>Choose a role, shape its personality, and give it the context to represent your business accurately.</p></div><div className="role-grid">{roles.map(([name, description], index) => <article className="role-card" key={name}><span className="role-number">0{index + 1}</span><h3>{name}</h3><p>{description}</p><span className="role-arrow">↗</span></article>)}</div></section>
    <section className="public-section steps-section" id="how-it-works"><p className="public-kicker">HOW IT WORKS</p><h2>From idea to answered call<br /><em>in three steps.</em></h2><div className="step-grid"><article><span>01</span><h3>Create your AI</h3><p>Choose an agent role and customize how it behaves.</p></article><article><span>02</span><h3>Give it instructions</h3><p>Tell it about your business, services, policies, and preferred style.</p></article><article><span>03</span><h3>Let HANDSFREE make the call</h3><p>Your AI speaks with real people and handles the conversation according to your instructions.</p></article></div></section>
    <section className="public-section demo-invite"><div><p className="public-kicker">SEE IT IN ACTION</p><h2>See what your AI<br /><em>can do.</em></h2><p>Bring us a real workflow. We will show you how an agent can handle it.</p></div><div className="request-list"><span>“Call this customer and confirm their appointment.”</span><span>“Follow up with everyone who requested a quote.”</span><span>“Answer incoming customer calls.”</span><span>“Book a reservation for a customer.”</span></div></section>
    <section className="public-section pricing-band" id="pricing"><div className="section-heading"><div><p className="public-kicker">SIMPLE, CLEAR PRICING</p><h2>Start with the calls<br />that matter most.</h2></div><p>Plans include AI calling minutes. Calling availability and rates may vary by destination.</p></div><div className="public-price-grid"><article><small>STARTER</small><strong>$29.95 <i>/ month</i></strong><b>100 AI minutes</b><a href="#demo">Talk to Sales ↗</a></article><article className="price-featured"><small>PROFESSIONAL <em>MOST POPULAR</em></small><strong>$95.99 <i>/ month</i></strong><b>400 AI minutes</b><a href="#demo">Talk to Sales ↗</a></article><article><small>BUSINESS</small><strong>$199.95 <i>/ month</i></strong><b>1,000 AI minutes</b><a href="#demo">Talk to Sales ↗</a></article></div></section>
    <section className="public-section demo-section" id="demo"><div className="demo-heading"><p className="public-kicker">BOOK A DEMO</p><h2>Bring us a call<br /><em>worth solving.</em></h2><p>Tell us what your business needs. We will tailor the conversation to the kind of agent you want to meet.</p></div><DemoForm /></section>
    <footer className="public-footer"><div><Link href="/" className="public-brand">HAND<span>SFREE</span><small>by VoiceDesk Technologies</small></Link><p>AI that works for your business.</p></div><div><b>PRODUCT</b><a href="#roles">AI Phone Agents</a><a href="#roles">Sales Agents</a><a href="#pricing">Pricing</a></div><div><b>COMPANY</b><a href="#demo">Book a Demo</a><Link href="/privacy">Privacy</Link><Link href="/terms">Terms</Link></div><div><b>CONTACT</b><a href="mailto:hello@voicedesk.tech">hello@voicedesk.tech</a><Link href="/auth/login">Sign In</Link></div><small className="footer-bottom">© {new Date().getFullYear()} VoiceDesk Technologies. All rights reserved.</small></footer>
  </main>;
}