"use client";

import { ChangeEvent, useEffect, useState } from "react";
import Link from "next/link";
import { apiRequest } from "@/lib/api/client";

type Settings = { first_name: string; last_name: string; business_name: string | null; country: string; ai_greeting_enabled: boolean; ai_greeting_text: string; default_call_duration_minutes: number; notifications_enabled: boolean; call_recordings_enabled: boolean };
const defaults: Settings = { first_name: "", last_name: "", business_name: null, country: "", ai_greeting_enabled: true, ai_greeting_text: "Hi, this is {agent_name}, an AI assistant calling on behalf of {business_name}.", default_call_duration_minutes: 5, notifications_enabled: true, call_recordings_enabled: false };
export default function SettingsPage() {
  const [settings, setSettings] = useState<Settings>(defaults); const [saved, setSaved] = useState(false); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false);
  useEffect(() => { apiRequest<Settings>("/api/settings").then((data) => setSettings({ ...defaults, ...data })).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }, []);
  function update(event: ChangeEvent<HTMLInputElement | HTMLTextAreaElement | HTMLSelectElement>) { const { name, value, type } = event.target; setSettings((current) => ({ ...current, [name]: type === "checkbox" ? (event.target as HTMLInputElement).checked : type === "number" ? Number(value) : value })); setSaved(false); }
  async function save() { setSaving(true); setSaved(false); setError(""); try { await apiRequest("/api/settings", { method: "PUT", body: JSON.stringify({ firstName: settings.first_name, lastName: settings.last_name, businessName: settings.business_name || null, country: settings.country, aiGreetingEnabled: settings.ai_greeting_enabled, aiGreetingText: settings.ai_greeting_text, defaultCallDurationMinutes: settings.default_call_duration_minutes, notificationsEnabled: settings.notifications_enabled, callRecordingsEnabled: settings.call_recordings_enabled }) }); setSaved(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to save settings"); } finally { setSaving(false); } }
  return <main className="phone-shell feature-page"><header className="app-header"><Link href="/" className="brand"><span className="brand-name">Hands<span>Free</span></span><span className="brand-parent">by VoiceDesk Technologies</span></Link><Link className="feature-back" href="/">Back to phone</Link></header><section className="feature-content form-page"><span className="eyebrow">ACCOUNT CONTROL</span><h1>Settings</h1>{loading ? <p className="feature-muted">Loading settings...</p> : <><section className="settings-panel"><div className="setting-copy"><h2>Profile</h2><p>Keep the details your agents and account notifications use.</p></div><div className="settings-grid"><label>First name<input name="first_name" value={settings.first_name} onChange={update} /></label><label>Last name<input name="last_name" value={settings.last_name} onChange={update} /></label><label>Business name <small>(optional)</small><input name="business_name" value={settings.business_name ?? ""} onChange={update} /></label><label>Country<input name="country" value={settings.country} onChange={update} /></label></div></section><section className="settings-panel"><div className="setting-copy"><h2>Call preferences</h2><p>Set guardrails for new AI call tasks.</p></div><label>Default call duration<select name="default_call_duration_minutes" value={settings.default_call_duration_minutes} onChange={update}><option value={5}>5 minutes</option><option value={15}>15 minutes</option><option value={30}>30 minutes</option><option value={60}>60 minutes</option></select></label><label className="toggle"><input type="checkbox" name="call_recordings_enabled" checked={settings.call_recordings_enabled} onChange={update} /><span className="toggle-track" />Allow recordings where legally appropriate</label></section><section className="settings-panel"><div className="setting-copy"><h2>AI greeting disclosure</h2><p>Choose whether your agents identify themselves as AI when a call begins.</p></div><label className="toggle"><input type="checkbox" name="ai_greeting_enabled" checked={settings.ai_greeting_enabled} onChange={update} /><span className="toggle-track" />Identify as an AI assistant</label><label>Greeting text<textarea name="ai_greeting_text" value={settings.ai_greeting_text} onChange={update} /></label></section><section className="settings-panel"><div className="setting-copy"><h2>Notifications</h2><p>Receive useful updates about calls, tasks, and account activity.</p></div><label className="toggle"><input type="checkbox" name="notifications_enabled" checked={settings.notifications_enabled} onChange={update} /><span className="toggle-track" />Enable account notifications</label></section>{error && <p className="auth-error">{error}</p>}<button className="primary-action" onClick={save} disabled={saving}>{saving ? "Saving settings..." : "Save settings"}<span>→</span></button>{saved && <p className="save-confirmation">Settings saved.</p>}</>}</section></main>;
}
