"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { apiRequest } from "@/lib/api/client";

type Billing = { plan: { period_end: string; included_minutes: number; used_minutes: number; plans: { name: string; monthly_price: number } } | null; trial: { trial_status: string; trial_expires_at: string; trial_minutes_granted: number; trial_minutes_used: number; trial_minutes_remaining: number } | null; balances: { trialMinutes: number; planMinutes: number; paygMinutes: number; totalMinutes: number }; calls: unknown[] };
export default function BillingPage() {
  const [billing, setBilling] = useState<Billing | null>(null); const [error, setError] = useState("");
  useEffect(() => { apiRequest<Billing>("/api/usage").then(setBilling).catch((reason: Error) => setError(reason.message)); }, []);
  const plan = billing?.plan; const trial = billing?.trial; const remaining = billing?.balances.planMinutes ?? 0;
  return <main className="phone-shell feature-page"><header className="app-header"><Link href="/" className="brand"><span className="brand-name">Hands<span>Free</span></span><span className="brand-parent">by VoiceDesk Technologies</span></Link><Link className="feature-back" href="/">Back to phone</Link></header><section className="feature-content billing-content"><span className="eyebrow">ACCOUNT CAPACITY</span><h1>Billing</h1>{error && <p className="auth-error">Unable to load billing. {error}</p>}{!error && !billing && <p className="feature-muted">Loading billing...</p>}{billing && <><section className="billing-summary"><div><small>CURRENT PLAN</small><h2>{plan?.plans.name ?? "No paid plan"}</h2><p>{plan ? `$${Number(plan.plans.monthly_price).toFixed(2)} monthly period` : "Choose a plan to continue calling"}</p></div><div><small>STATUS</small><strong>{plan ? "Active" : trial?.trial_status === "active" ? "Trial" : "Ended"}</strong><p>{plan ? `Ends ${new Date(plan.period_end).toLocaleDateString()}` : trial ? `Trial ends ${new Date(trial.trial_expires_at).toLocaleDateString()}` : "No active entitlement"}</p></div></section><p className="billing-note">Plans are one-time monthly purchases and do not automatically renew. Renew your plan each month after it ends.</p><div className="billing-actions"><Link href="/pricing" className="primary-action">View plans <span>→</span></Link><Link href="/billing/payg" className="secondary-action">Buy more minutes</Link></div><section className="usage-stat-grid"><div className="usage-card"><small>PLAN MINUTES</small><h2>{remaining.toFixed(1)} remaining</h2><p>Included: {plan?.included_minutes ?? 0} minutes</p></div><div className="usage-card"><small>PAY-AS-YOU-GO</small><h2>{billing.balances.paygMinutes.toFixed(1)} remaining</h2><p>One-time purchased minutes</p></div><div className="usage-card"><small>TRIAL</small><h2>{billing.balances.trialMinutes.toFixed(1)} remaining</h2><p>{trial?.trial_status === "active" ? "10 total minutes · 3 days" : "Trial ended"}</p></div></section></>}</section></main>;
}