"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { apiRequest } from "@/lib/api/client";

type Contact = { id: string; first_name: string; last_name: string; company: string | null; phone_number: string; favorite: boolean };
export default function ContactsPage() {
  const [contacts, setContacts] = useState<Contact[]>([]); const [open, setOpen] = useState(false); const [error, setError] = useState(""); const [form, setForm] = useState({ firstName: "", lastName: "", company: "", phoneNumber: "", email: "" });
  const load = () => apiRequest<Contact[]>("/api/contacts").then(setContacts).catch((reason: Error) => setError(reason.message));
  useEffect(() => { load(); }, []);
  async function add(event: FormEvent) { event.preventDefault(); try { await apiRequest("/api/contacts", { method: "POST", body: JSON.stringify({ ...form, company: form.company || null, email: form.email || null }) }); setForm({ firstName: "", lastName: "", company: "", phoneNumber: "", email: "" }); setOpen(false); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to add contact"); } }
  async function remove(id: string) { try { await apiRequest(`/api/contacts/${id}`, { method: "DELETE" }); setContacts((current) => current.filter((contact) => contact.id !== id)); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to delete contact"); } }
  return <main className="phone-shell feature-page"><header className="app-header"><Link href="/" className="brand"><span className="brand-name">Hands<span>Free</span></span><span className="brand-parent">by VoiceDesk Technologies</span></Link><Link className="feature-back" href="/">Back to phone</Link></header><section className="feature-content"><div className="feature-heading"><div><span className="eyebrow">YOUR PEOPLE</span><h1>Contacts</h1></div><button className="primary-action feature-action" onClick={() => setOpen(true)}>Add contact <span>+</span></button></div>{error && <p className="auth-error">{error}</p>}{contacts.length === 0 && !error && <div className="empty-state"><h2>No contacts yet.</h2><p>Add someone you call often to find them quickly.</p><button className="primary-action" onClick={() => setOpen(true)}>Add contact <span>→</span></button></div>}<div className="contact-list">{contacts.map((contact) => <article className="contact-row" key={contact.id}><span className="agent-avatar">{contact.first_name.slice(0, 1).toUpperCase()}</span><div><h2>{contact.first_name} {contact.last_name}</h2><p>{contact.company || contact.phone_number}</p><small>{contact.phone_number}</small></div><a className="row-call" href={`tel:${contact.phone_number}`} aria-label={`Call ${contact.first_name}`}>☎</a><button className="row-delete" onClick={() => remove(contact.id)} aria-label={`Delete ${contact.first_name}`}>×</button></article>)}</div></section>{open && <div className="modal-layer"><form className="call-modal" onSubmit={add}><button type="button" className="modal-close" onClick={() => setOpen(false)} aria-label="Close">×</button><span className="eyebrow">NEW CONTACT</span><h1>Add a contact</h1>{([["firstName", "First name"], ["lastName", "Last name"], ["company", "Company"], ["phoneNumber", "Phone number"], ["email", "Email"]] as const).map(([key, label]) => <label key={key}>{label}<input type={key === "email" ? "email" : "text"} value={form[key]} onChange={(event) => setForm((current) => ({ ...current, [key]: event.target.value }))} required={key === "firstName" || key === "phoneNumber"} /></label>)}<button className="primary-action">Save contact <span>→</span></button></form></div>}</main>;
}
