"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { apiRequest } from "@/lib/api/client";

type NumberRow = { id: string; phone_number: string; country: string; status: string; provider: string; ai_agents: { name: string } | null };
type Agent = { id: string; name: string };
export default function NumbersPage() { const [numbers, setNumbers] = useState<NumberRow[]>([]); const [agents, setAgents] = useState<Agent[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [editing, setEditing] = useState<string | null>(null); const [agentId, setAgentId] = useState("");
  function load() { setLoading(true); apiRequest<NumberRow[]>("/api/numbers").then(setNumbers).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); }
  useEffect(() => { apiRequest<NumberRow[]>("/api/numbers").then(setNumbers).catch((reason: Error) => setError(reason.message)).finally(() => setLoading(false)); apiRequest<Agent[]>("/api/agents").then(setAgents).catch(() => undefined); }, []);
  async function assign(id: string) { try { await apiRequest(`/api/numbers/${id}`, { method: "PATCH", body: JSON.stringify({ agentId: agentId || null }) }); setEditing(null); load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to configure number"); } }
  return <main className="phone-shell feature-page"><header className="app-header"><Link href="/" className="brand"><span className="brand-name">Hands<span>Free</span></span><span className="brand-parent">by VoiceDesk Technologies</span></Link><Link className="feature-back" href="/">Back to phone</Link></header><section className="feature-content"><div className="feature-heading"><div><span className="eyebrow">TELEPHONY</span><h1>My Numbers</h1><p className="lead-copy">Manage the real phone numbers connected to your HandsFree account.</p></div></div>{error && <p className="auth-error">Unable to load numbers. {error}</p>}{loading ? <p className="feature-muted">Loading your numbers...</p> : numbers.length === 0 ? <div className="empty-state"><h2>No phone numbers yet.</h2><p>Numbers must be provisioned through a configured telephony provider.</p></div> : <div className="contact-list">{numbers.map((item) => <article className="contact-row" key={item.id}><span className="agent-avatar">⌕</span><div><h2>{item.phone_number}</h2><p>{item.country} · {item.provider} · {item.status}</p><small>{item.ai_agents?.name ? `Assigned to ${item.ai_agents.name}` : "No agent assigned"}</small>{editing === item.id && <div className="inline-editor"><select value={agentId} onChange={(event) => setAgentId(event.target.value)}><option value="">No assigned agent</option>{agents.map((agent) => <option value={agent.id} key={agent.id}>{agent.name}</option>)}</select><button className="primary-action" onClick={() => assign(item.id)}>Save <span>→</span></button></div>}</div><button className="row-call" onClick={() => { setEditing(editing === item.id ? null : item.id); setAgentId(agents.find((agent) => agent.name === item.ai_agents?.name)?.id ?? ""); }} aria-label="Configure number">⚙</button></article>)}</div>}</section></main>; }
